import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppSidebar from "@/components/app-sidebar";
import AuthProvider from "@/components/auth-provider";
import { TeamProvider } from "@/contexts/team-context";
import { LabelProvider } from "@/contexts/label-context";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${inter.className} h-full antialiased`}
    >
      <body className="min-h-full">
        <AuthProvider>
          <TeamProvider>
            <LabelProvider>
              <AppSidebar>{children}</AppSidebar>
            </LabelProvider>
          </TeamProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
